[package]
name = "millis"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.53"
thiserror = "1.0.30"
clap = { version = "3.0.14", features = ["derive"] }
chrono = "0.4.19"